### ISSUE TITLE
macOS 12, Monterey Support

### ISSUE THREAD

**Issue by khronokernel** [dortania/OpenCore-Legacy-Patcher#271]
Today Apple announced macOS 12, Monterey and with it more models have been dropped:

<details>
<summary>Dropped SMBIOS</summary>

* iMac14,4
* iMac15,1
* MacBook8,1
* MacBookAir6,1
* MacBookAir6,2
* MacBookPro11,1
* MacBookPro11,2
* MacBookPro11,3
</details>
<br>

Additionally, a the time of writing we've found that the following hardware has been dropped:

* Intel HD 4000 drivers

## TODO List

* [x] Add newly dropped SMBIOS
* [x] Investigate Boot Hangs with macOS 12
* [x] Investigate WindowServer crash on non-Metal GPUs
* [x] Investigate re-adding Intel HD 4000 support
* [x] Investigate broken Legacy Networking Kexts (ElCap-Mojave)
* [x] Investigate broken Bluetooth
* [x] Update Innie and NightShiftEnabler to not rely on `-lilubetaall`
* [x] Fix userspace patching

**Comment by khronokernel** [comment]
Closing as proper issues have been created for each issue
